### ISSUE TITLE
A question about REQ-ROUTER

### ISSUE THREAD

**Issue by surik** [zeromq/ezmq#26]
I use REQ and ROUTER pattern. REQ sends empty frame at start and waiting for it on response.
Is it normal that empty frame delivered on ROUTER application level? Can ezmq processing it on own level?

**Comment by RoadRunnr** [comment]
ezmq is not supposed to manipulate the frames is gets, so it can't do any about the empty frame.

Sending and recieving empty frames should work both on REQ and on ROUTER sockets.

Can you show in a simple example of what is not working and what the expected behavior is?

**Comment by surik** [comment]
@RoadRunnr yes, I have example

```erlang
-module(ezmq_test).

-compile([export_all]).

test() ->
    application:ensure_all_started(ezmq),

    {ok, Server}  = ezmq:socket([{type, router}]),
    ok = ezmq:bind(Server, tcp, 28212, [inet, {reuseaddr, true}, {ip, {0,0,0,0}}]),

    {ok, Client} = ezmq:socket([{type, req}]),
    ok = ezmq:connect(Client, tcp, {0,0,0,0}, 28212, [inet]),

    ok = ezmq:send(Client, [<<"Hello">>]),

    {ok, {Peer, _ReceivedFromClient}} = ezmq:recv(Server),
    ok = ezmq:send(Server, {Peer, [<<"World">>]}),

    {ok, _ReceivedFromServer} = ezmq:recv(Client),

    ok.
~~~

But client don't receive response, because server didn't add empty frame when send response message
My question is why I have to think about zmq protocol level when I'm using this library?

**Comment by Asmod4n** [comment]
You could try out to swap the REQ with a DEALER sock, which doesn't need the empty frame.

**Comment by surik** [comment]
@Asmod4n you right, but my question was about 'why I on my application level have to worry about protocol level'. I'd read more about zmq and now realized that it is low level protocol

The prehistory of this question was: I have server with ROUTER socket and client with DEALER sock - it works well. But if by any reason third-party client are trying to connect to my server with REQ socket (it is normal for zmq, isn't it?) I have problem with needed processing the empty frame, I expected that zmq does itself, but not so easy :)

Anyway, documentation about zmq brought me some new knowledge about how it works.
